//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyStorage
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.Sales = new HashSet<Sales>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<int> type_id { get; set; }
        public Nullable<int> gender_id { get; set; }
        public Nullable<int> size_id { get; set; }
        public string color { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<double> price_unit { get; set; }
        public string description { get; set; }
        public Nullable<bool> available { get; set; }
        public Nullable<int> storage_id { get; set; }
    
        public virtual Genders Genders { get; set; }
        public virtual Sizes Sizes { get; set; }
        public virtual Storages Storages { get; set; }
        public virtual Types Types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sales> Sales { get; set; }
    }
}
