//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyStorage
{
    using System;
    using System.Collections.Generic;
    
    public partial class test_tb
    {
        public int id { get; set; }
        public string tname { get; set; }
        public Nullable<int> num { get; set; }
    }
}
